Feat/scan type
distributedio/titan pull request #216
Opened 2021-02-08 15:34 UTC by nioshield

- implement SCAN TYPE subcommand

2021-02-10 05:57 UTC, arthurkiller requested changes

2021-02-10 05:57 UTC, arthurkiller commented on command/keys.go
> +			usePattern = !(pattern[0] == '*' && len(pattern) == 1)
根据 && 的计算优先级顺序，是否应该先判断 len ，再判断 pattern[0], 避免空指针

2021-02-10 05:57 UTC, arthurkiller commented on command/keys.go
>  		if count <= 0 {
是否改成 switch case 更加清晰？

2021-03-31 03:46 UTC, shafreeck approved these changes
LGTM

Maybe you should update the related documents as well

2021-03-31 03:50 UTC, merged